#docker compose para desplegar en local
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: adminuser
      POSTGRES_PASSWORD: password1234
      POSTGRES_DB: near_parkings
    ports:
      - "5434:5432"
    volumes:
      - near_parkings_pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    ports:
    - "8000:8000"
    volumes:
    - ./backend:/app
    depends_on:
    - db
    environment:
      DATABASE_URL: postgresql+psycopg://adminuser:password1234@db:5432/near_parkings

  migrate:
    build:
      context: ./backend
    working_dir: /app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg://adminuser:password1234@db:5432/near_parkings
    command: alembic upgrade head
volumes:
  near_parkings_pgdata: